"""empty message

Revision ID: 52aadab833d6
Revises: a5cffa318ac2
Create Date: 2024-11-25 19:07:28.826621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52aadab833d6'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('weather')
        batch_op.drop_column('description')
        batch_op.drop_column('population')
        batch_op.drop_column('name')

    op.drop_table('planet')
    # ### end Alembic commands ###
